version: '2'
volumes:
  logs:
  postgres-data:

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
      - logs:/code/logs
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env-local

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env-local

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command:  celery -A core worker -l info --concurrency=4
    volumes:
      - ./src:/code
      - logs:/code/logs
    depends_on:
      - redis
      - db
    env_file:
      - .env-local

  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - ./src:/code
      - logs:/code/logs
    depends_on:
      - celery
      - redis
    env_file:
      - .env-local

  flower:
    image: mher/flower:0.9.7
    ports:
      - "5555:5555"
    depends_on:
      - redis
    env_file:
      - .env-local