#TODO заполнить файл
#TODO файл не готов, взят из tn-gis

version: '3.8'

services:
  gis-api:
    image: ${REGISTRY}/${ENVIRONMENT}-gis-api:${DOCKER_TAG}
    command: ./start.sh
    container_name: ${STAND}-gis-api
    volumes:
      - logs-gis-api:/code/logs
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    restart: unless-stopped
    networks: 
      - gis-network


  postgres:
    image: ${REGISTRY_SHARED}/postgres:13
    container_name: ${STAND}-postgres
    expose:
      - "5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks: 
      - gis-network

  redis:
    image: ${REGISTRY_SHARED}/redis:6.2.1-alpine
    container_name: ${STAND}-redis
    expose:
      - "6379"
    env_file:
      - .env
    restart: unless-stopped

  celery:
    image: ${REGISTRY}/${ENVIRONMENT}-gis-api:${DOCKER_TAG}
    command:  celery -A core worker -l info --concurrency=4
    container_name: ${STAND}-gis-celery
    volumes:
      - logs-worker:/code/logs
    depends_on:
      - redis
      - postgres
      - gis-api
    env_file:
      - .env
    restart: unless-stopped
    networks: 
      - gis-network

  celery-beat:
    image: ${REGISTRY}/${ENVIRONMENT}-gis-api:${DOCKER_TAG}
    command: celery -A core beat -l info
    container_name: ${STAND}-gis-celery-beat
    volumes:
      - logs-beater:/code/logs
    depends_on:
      - celery
      - redis
      - gis-api
    env_file:
      - .env
    restart: unless-stopped
    networks: 
      - gis-network

  flower:
    image: ${REGISTRY_SHARED}/flower:0.9.7
    container_name: ${STAND}-flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
    networks: 
      - gis-network

networks:
  gis-network:
    name: ${STAND}-gis-network
    ipam:
        driver: default
        # 61 - GS application number 
        config:
            - subnet: 172.61.${STAND_SUBNET}.0/24
              gateway: 172.61.${STAND_SUBNET}.1

volumes:
  logs-gis-api:
    driver: local
  logs-worker:
    driver: local
  logs-beater:
    driver: local
  postgres-data:
    driver: local